Tracker:AddLocations("locations/south clock town.json")
Tracker:AddLocations("locations/north clock town.json")
Tracker:AddLocations("locations/east clock town.json")
Tracker:AddLocations("locations/west clock town.json")
Tracker:AddLocations("locations/stock pot inn.json")
Tracker:AddLocations("locations/termina field.json")
Tracker:AddLocations("locations/milk road.json")
Tracker:AddLocations("locations/romani ranch.json")
Tracker:AddLocations("locations/road to swamp.json")
Tracker:AddLocations("locations/southern swamp.json")
Tracker:AddLocations("locations/woodfall.json")
Tracker:AddLocations("locations/deku palace.json")
Tracker:AddLocations("locations/mountain village.json")
Tracker:AddLocations("locations/twin island.json")
Tracker:AddLocations("locations/goron village.json")
Tracker:AddLocations("locations/path to snowhead.json")
Tracker:AddLocations("locations/great bay coast.json")
Tracker:AddLocations("locations/zora cape.json")
Tracker:AddLocations("locations/zora hall")